Repository dogtagpki/pki, pull requests merged in 2018-10, with the labels that each got.

#65 Fix doctag in RequestStatusAdapter
  base/common/src/com/netscape/certsrv/request/RequestStatusAdapter.java
Labels: enhancement

#71 Refactoring `split_cert_id` for code reusability
  base/server/python/pki/server/__init__.py
  base/server/python/pki/server/cli/cert.py
Labels: refactor

#72 Refactoring `temp cert creation`
  base/server/python/pki/server/__init__.py
  base/server/python/pki/server/cli/cert.py
Labels: refactor

#76 Fixed password prompt in pki CLI (PKI 10.5)
  base/java-tools/src/com/netscape/cmstools/cli/MainCLI.java
Labels: bug

#77 Added subsystem config management commands
  base/server/python/pki/server/cli/ca.py
  base/server/python/pki/server/cli/config.py
  base/server/python/pki/server/cli/kra.py
  base/server/python/pki/server/cli/ocsp.py
  base/server/python/pki/server/cli/tks.py
  base/server/python/pki/server/cli/tps.py
Labels: CLI Automation, enhancement
