Repository dogtagpki/pki, pull requests merged in 2019-08, with the labels that each got.

#231 Fix 'pkidestroy --force' to pickup correct instance name
  base/server/python/pki/server/deployment/pkiparser.py
  base/server/python/pki/server/deployment/scriptlets/security_databases.py
  base/server/python/pki/server/deployment/scriptlets/selinux_setup.py
  base/server/python/pki/server/pkidestroy.py
Labels: needs-review, question

#237 Remove duplicated netscape.security tests
  base/util/test/CMakeLists.txt
  base/util/test/com/netscape/security/extensions/GenericASN1ExtensionTest.java
  base/util/test/com/netscape/security/util/BMPStringTest.java
  base/util/test/com/netscape/security/util/IA5StringTest.java
  base/util/test/com/netscape/security/util/JSSUtil.java
  base/util/test/com/netscape/security/util/PrintableStringTest.java
  base/util/test/com/netscape/security/util/StringTestUtil.java
  base/util/test/com/netscape/security/util/TeletexStringTest.java
  base/util/test/com/netscape/security/util/UTF8StringTest.java
  base/util/test/com/netscape/security/util/UniversalStringTest.java
  base/util/test/com/netscape/security/x509/ConverterTestUtil.java
  base/util/test/com/netscape/security/x509/DirStrConverterTest.java
  base/util/test/com/netscape/security/x509/GenericValueConverterTest.java
  base/util/test/com/netscape/security/x509/IA5StringConverterTest.java
  base/util/test/com/netscape/security/x509/PrintableConverterTest.java
Labels: refactor

#235 LWCA key gen: use parent key size
  base/ca/src/com/netscape/ca/CertificateAuthority.java
Labels: needs-review
