Repository dogtagpki/pki, pull requests merged in 2019-02, with the labels that each got.

#171 Fix Nuxwdog to accept HSM password
  base/server/scripts/pki-server-nuxwdog
Labels: bug

#172 Fix Nuxwdog to accept HSM password
  base/server/scripts/pki-server-nuxwdog
Labels: backport, bug

#120 Sync spec from pki-core.spec
  pki.spec
Labels: bug

#123 Remove duplicate getKeyWrapAlgorithmFromOID implementation
  base/util/src/com/netscape/cmsutil/crypto/CryptoUtil.java
Labels: refactor
