Repository dogtagpki/pki, pull requests merged in 2019-01, with the labels that each got.

#128 Rename org->orgName in CertificatePoliciesExtDefault
  base/server/cms/src/com/netscape/cms/profile/def/CertificatePoliciesExtDefault.java
Labels: bug

#130 Add make to BuildRequires in pki.spec
  pki.spec
Labels: bug

#140 Rename `nuxwdog` script
  base/server/CMakeLists.txt
  base/server/scripts/pki-server-nuxwdog
  base/server/share/lib/systemd/system/pki-tomcatd-nuxwdog@.service
  docs/admin/Nuxwdog.md
  pki.spec
Labels: bug

#145 Fix pylint 2.2 errors "Unnecessary pass statement"
  base/common/python/pki/crypto.py
  base/common/python/pki/key.py
Labels: refactor

#147 Version check for dscreate for 1.4.20 and correcting option from from…
  tests/dogtag/pytest-ansible/installation/roles/Test_Execution/tasks/configure_ldap.yml
Labels: needs-review

#149 Bug fix for Nuxwdog
  base/server/scripts/pki-server-nuxwdog
  pki.spec
Labels: bug

#150 Bug fix for Nuxwdog (#149)
  base/server/scripts/pki-server-nuxwdog
  pki.spec
Labels: backport, bug

#144 Minor improvements to PKCS10Client man page
  base/java-tools/man/man1/PKCS10Client.1
Labels: needs-review, question
