Repository dogtagpki/pki, pull requests merged in 2020-03, with the labels that each got.

#332 Remove unused, unnecessary RADIUS implementation
  base/util/src/com/netscape/cmsutil/radius/AccessAccept.java
  base/util/src/com/netscape/cmsutil/radius/AccessChallenge.java
  base/util/src/com/netscape/cmsutil/radius/AccessReject.java
  base/util/src/com/netscape/cmsutil/radius/AccessRequest.java
  base/util/src/com/netscape/cmsutil/radius/Attribute.java
  base/util/src/com/netscape/cmsutil/radius/AttributeFactory.java
  base/util/src/com/netscape/cmsutil/radius/AttributeSet.java
  base/util/src/com/netscape/cmsutil/radius/Authenticator.java
  base/util/src/com/netscape/cmsutil/radius/CHAPChallengeAttribute.java
  base/util/src/com/netscape/cmsutil/radius/CHAPPasswordAttribute.java
  base/util/src/com/netscape/cmsutil/radius/CallbackIdAttribute.java
  base/util/src/com/netscape/cmsutil/radius/CallbackNumberAttribute.java
  base/util/src/com/netscape/cmsutil/radius/CallerStationIdAttribute.java
  base/util/src/com/netscape/cmsutil/radius/CallingStationIdAttribute.java
  base/util/src/com/netscape/cmsutil/radius/ChallengeException.java
  base/util/src/com/netscape/cmsutil/radius/FilterIdAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedAppleTalkLinkAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedAppleTalkNetworkAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedAppleTalkZoneAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedCompressionAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedIPAddressAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedIPNetmaskAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedIPXNetworkAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedMTUAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedProtocolAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedRouteAttribute.java
  base/util/src/com/netscape/cmsutil/radius/FramedRoutingAttribute.java
  base/util/src/com/netscape/cmsutil/radius/GenericAttribute.java
  base/util/src/com/netscape/cmsutil/radius/IdleTimeoutAttribute.java
  base/util/src/com/netscape/cmsutil/radius/LoginIPHostAttribute.java
  base/util/src/com/netscape/cmsutil/radius/LoginLATGroupAttribute.java
  base/util/src/com/netscape/cmsutil/radius/LoginLATNodeAttribute.java
  base/util/src/com/netscape/cmsutil/radius/LoginLATPortAttribute.java
  base/util/src/com/netscape/cmsutil/radius/LoginLATServiceAttribute.java
  base/util/src/com/netscape/cmsutil/radius/LoginServiceAttribute.java
  base/util/src/com/netscape/cmsutil/radius/LoginTCPPortAttribute.java
  base/util/src/com/netscape/cmsutil/radius/NASClassAttribute.java
  base/util/src/com/netscape/cmsutil/radius/NASIPAddressAttribute.java
  base/util/src/com/netscape/cmsutil/radius/NASIdentifierAttribute.java
  base/util/src/com/netscape/cmsutil/radius/NASPacket.java
  base/util/src/com/netscape/cmsutil/radius/NASPortAttribute.java
  base/util/src/com/netscape/cmsutil/radius/NASPortTypeAttribute.java
  base/util/src/com/netscape/cmsutil/radius/Packet.java
  base/util/src/com/netscape/cmsutil/radius/PacketFactory.java
  base/util/src/com/netscape/cmsutil/radius/PortLimitAttribute.java
  base/util/src/com/netscape/cmsutil/radius/ProxyStateAttribute.java
  base/util/src/com/netscape/cmsutil/radius/RadiusConn.java
  base/util/src/com/netscape/cmsutil/radius/RejectException.java
  base/util/src/com/netscape/cmsutil/radius/ReplyMessageAttribute.java
  base/util/src/com/netscape/cmsutil/radius/RequestAuthenticator.java
  base/util/src/com/netscape/cmsutil/radius/ResponseAuthenticator.java
  base/util/src/com/netscape/cmsutil/radius/ServerPacket.java
  base/util/src/com/netscape/cmsutil/radius/ServiceTypeAttribute.java
  base/util/src/com/netscape/cmsutil/radius/SessionTimeoutAttribute.java
  base/util/src/com/netscape/cmsutil/radius/StateAttribute.java
  base/util/src/com/netscape/cmsutil/radius/TerminationActionAttribute.java
  base/util/src/com/netscape/cmsutil/radius/UserNameAttribute.java
  base/util/src/com/netscape/cmsutil/radius/UserPasswordAttribute.java
  base/util/src/com/netscape/cmsutil/radius/VendorSpecificAttribute.java
Labels: enhancement

#344 Add warning about CVE-2020-1938
  base/server/etc/default.cfg
Labels: enhancement

#349 Remove MAX_NUM_POLICIES hardcoded limit
  base/server/cms/src/com/netscape/cms/profile/def/CertificatePoliciesExtDefault.java
Labels: needs-review

#355 Patch ECAdminCertProfile upgrade script
  base/server/upgrade/10.8.2/01-FixECAdminCertProfile.py
Labels: bug
