Repository dogtagpki/pki, pull requests merged in 2020-02, with the labels that each got.

#321 Fix interactive DS configuration
  base/server/python/pki/server/deployment/__init__.py
  base/server/python/pki/server/pkispawn.py
Labels: bug

#330 Convert multiline script to use literal style scalar
  .travis.yml
  travis/builder-init.sh
  travis/ca-create.sh
  travis/ca-remove.sh
  travis/ds-create.sh
  travis/ds-remove.sh
  travis/ipa-init.sh
  travis/ipa-test.sh
  travis/kra-create.sh
  travis/kra-remove.sh
  travis/ocsp-create.sh
  travis/ocsp-remove.sh
  travis/pki-build.sh
  travis/pki-init.sh
  travis/pki-install.sh
  travis/tks-create.sh
  travis/tks-remove.sh
  travis/tps-create.sh
  travis/tps-remove.sh
Labels: CI, bug

#333 Migrate away from deployer.* to pki.util.* in pkidestroy
  base/server/python/pki/server/deployment/scriptlets/infrastructure_layout.py
  base/server/python/pki/server/deployment/scriptlets/instance_layout.py
  base/server/python/pki/server/deployment/scriptlets/security_databases.py
  base/server/python/pki/server/deployment/scriptlets/subsystem_layout.py
  base/server/python/pki/server/deployment/scriptlets/webapp_deployment.py
Labels: enhancement

#336 Refactor CTResponse
  base/ca/src/CMakeLists.txt
  base/ca/src/com/netscape/ca/CAService.java
  base/ca/src/com/netscape/ca/CTParser.java
  base/ca/src/com/netscape/ca/CTResponse.java
Labels: refactor
