Repository dogtagpki/pki, pull requests merged in 2020-09, with the labels that each got.

#546 Move COPR to v10.9
  .github/workflows/required-tests.yml
  tests/dogtag/pytest-ansible/provision/post_provision.yml
Labels: CI, bug

#545 CI: Use NFS instead of virtualbox guest
  .github/workflows/qe-tests.yml
  ci/Vagrantfile
Labels: CI

#548 Keep JAVA_HOME in tomcat.conf
  base/server/python/pki/server/cli/migrate.py
  base/server/share/conf/tomcat.conf
Labels: bug

#547 CI: Run healthcheck in CI pipeline
  .github/workflows/required-tests.yml
  ci/ipa-test.sh
Labels: CI

#552 Update README doc
  README.md
Labels: Documentation, Enhancement

#566 Fix HTTP Request formatting in AdminConnection
  base/console/src/com/netscape/admin/certsrv/connection/AdminConnection.java
Labels: Backport

#570 Remove net-tools
  pki.spec
Labels: dependencies
