Repository dogtagpki/pki, pull requests merged in 2020-04, with the labels that each got.

#368 Temporarily disable PKI COPR repo for SSLEngine
  travis/pki-init.sh
Labels: CI, bug

#379 Add TPS Auditor group
  base/tps/shared/conf/db.ldif
Labels: backport, bug

#381 Include new ecj.jar path in pki.policy
  base/server/share/conf/pki.policy
Labels: bug

#383 Add GH actions to CI
  .github/workflows/required-tests.yml
  travis/runner-init.sh
Labels: CI, enhancement

#398 Refactor Certificate Transparency request - JSON parameter
  base/ca/src/com/netscape/ca/CAService.java
  base/ca/src/com/netscape/ca/CTRequest.java
Labels: refactor
