Repository dogtagpki/pki, pull requests merged in 2020-08, with the labels that each got.

#498 Fix Secure connection issue when server is down
  base/server/python/pki/server/__init__.py
  base/server/python/pki/server/cli/cert.py
Labels: bug

#494 Move from sudo to runuser
  .github/workflows/required-tests.yml
  base/server/python/pki/server/__init__.py
  base/server/python/pki/server/instance.py
  base/server/python/pki/server/subsystem.py
Labels: enhancement, needs-review

#510 Fix runuser to use absolute path
  base/server/python/pki/server/__init__.py
  base/server/python/pki/server/instance.py
  base/server/python/pki/server/subsystem.py
Labels: bug, regression

#515 Add nuxwdog status to pki-server status
  base/server/python/pki/server/cli/__init__.py
Labels: bug

#521 Make PKI use JDK8 everywhere again
  pki.spec
Labels: bug
