Repository dogtagpki/pki, pull requests merged in 2020-01, with the labels that each got.

#306 Add support for running PKI under GDB
  base/server/python/pki/server/__init__.py
  base/server/python/pki/server/cli/__init__.py
  base/server/python/pki/server/instance.py
Labels: enhancement

#301 PKI healthcheck tool
  base/server/CMakeLists.txt
  base/server/healthcheck/CMakeLists.txt
  base/server/healthcheck/healthcheck.conf
  base/server/healthcheck/pki/server/healthcheck/core/__init__.py
  base/server/healthcheck/pki/server/healthcheck/core/main.py
  base/server/healthcheck/pki/server/healthcheck/meta/__init__.py
  base/server/healthcheck/pki/server/healthcheck/meta/csconfig.py
  base/server/healthcheck/pki/server/healthcheck/meta/plugin.py
  base/server/healthcheck/setup.py
  pki.spec
Labels: needs-review

#309 Fix FIPS detection
  base/common/python/pki/__init__.py
Labels: bug
