Repository dogtagpki/pki, pull requests merged in 2020-07, with the labels that each got.

#475 Measure individual test execution time
  tests/dogtag/pytest-ansible/pytest/performance_test/test_cert_enrollment.py
  tests/dogtag/pytest-ansible/pytest/performance_test/test_cert_revocation.py
Labels: CI, enhancement

#478 CI: Change the entrypoint to /sbin/init
  .github/workflows/required-tests.yml
  ci/Dockerfile
  ci/runner-init.sh
Labels: CI

#484 Fix build with CMake out-of-source build change
  pki.spec
Labels: bug

#399 Move to versionless java dependencies
  CMakeLists.txt
  base/common/python/pki/cli/main.py
  base/common/share/etc/pki.conf
  base/java-tools/templates/pki_java_command_wrapper.in
  base/java-tools/templates/pretty_print_cert_command_wrapper.in
  base/java-tools/templates/pretty_print_crl_command_wrapper.in
  base/server/python/pki/server/__init__.py
  base/server/python/pki/server/subsystem.py
  pki.spec
Labels: bug

#489 Fix HTTP Request formatting in AdminConnection
  base/console/src/com/netscape/admin/certsrv/connection/AdminConnection.java
Labels: bug

#490 Support exporting CA certificate from HSM installs
  base/server/python/pki/server/cli/migrate.py
Labels: bug

#492 Fix pylint issue in healthcheck
  base/server/healthcheck/pki/server/healthcheck/certs/plugin.py
  base/server/healthcheck/pki/server/healthcheck/meta/plugin.py
Labels: regression

#488 Re-fix sanitization in CMSTemplate
  base/server/src/com/netscape/cms/servlet/common/CMSTemplate.java
Labels: bug

#376 Add TPS Auditor role
  base/tps/shared/conf/db.ldif
Labels: bug

#497 Move PrettyPrint{Cert,Crl} to PKI_LIB classpath
  base/java-tools/templates/pretty_print_cert_command_wrapper.in
  base/java-tools/templates/pretty_print_crl_command_wrapper.in
Labels: bug
