Repository dogtagpki/pki, pull requests merged in 2020-06, with the labels that each got.

#432 Helathcheck: RHCS trust flags
  base/server/healthcheck/pki/server/healthcheck/certs/trustflags.py
  base/server/healthcheck/pki/server/healthcheck/meta/connectivity.py
Labels: enhancement

#433 Include trust flag info in pki-server cert-* operation
  base/common/python/pki/nssdb.py
  base/server/python/pki/server/cli/cert.py
  base/server/python/pki/server/subsystem.py
Labels: enhancement

#439 Remove Tomcat 7.0, Tomcat 8.0 specific configs
  base/server/tomcat-7.0/CMakeLists.txt
  base/server/tomcat-7.0/conf/Catalina/localhost/ROOT.xml
  base/server/tomcat-7.0/conf/Catalina/localhost/pki.xml
  base/server/tomcat-7.0/conf/catalina.properties
  base/server/tomcat-7.0/conf/server.xml
  base/server/tomcat-7.0/src/CMakeLists.txt
  base/server/tomcat-7.0/src/com/netscape/cms/tomcat/ProxyRealm.java
  base/server/tomcat-7.0/src/com/netscape/cms/tomcat/SSLAuthenticatorWithFallback.java
  base/server/tomcat-7.0/src/pki-tomcat.mf
  base/server/tomcat-8.0/CMakeLists.txt
  base/server/tomcat-8.0/conf/Catalina/localhost/ROOT.xml
  base/server/tomcat-8.0/conf/Catalina/localhost/pki.xml
  base/server/tomcat-8.0/conf/catalina.properties
  base/server/tomcat-8.0/conf/server.xml
  base/server/tomcat-8.0/src/CMakeLists.txt
  base/server/tomcat-8.0/src/com/netscape/cms/tomcat/ProxyRealm.java
  base/server/tomcat-8.0/src/com/netscape/cms/tomcat/SSLAuthenticatorWithFallback.java
  base/server/tomcat-8.0/src/pki-tomcat.mf
Labels: refactor

#441 Healthcheck: RHCS healthcheck expiration
  base/server/healthcheck/pki/server/healthcheck/certs/expiration.py
Labels: enhancement

#446 CVE Fix - XSS in PathLength attribute in CA agent web page
  base/ca/shared/webapps/ca/agent/ca/ProfileReview.template
  base/server/src/com/netscape/cms/servlet/base/CMSServlet.java
Labels: bug

#452 Fix reflected XSS attack when hitting getCookie endpoint
  base/server/src/com/netscape/cms/servlet/csadmin/GetCookie.java
Labels: bug

#453 Added client-side prevention for XSS in recoveryID endpoint
  base/kra/shared/webapps/kra/agent/kra/GrantRecovery.html
Labels: bug

#455 Fix javadoc build on Debian
  base/javadoc/CMakeLists.txt
Labels: bug

#457 Use password during NSS DB creation
  base/java-tools/src/com/netscape/cmstools/cli/MainCLI.java
Labels: bug

#454 Set -Dcom.redhat.fips=false in Tomcat config
  base/server/share/conf/tomcat.conf
  base/server/upgrade/10.9.0/03-DisableOpenJDKFIPS.py
Labels: bug, enhancement

#459 Fix extraction of CA certificate
  base/common/python/pki/nssdb.py
  base/server/python/pki/server/__init__.py
Labels: bug
